spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:h2:mem:gametestdb
    username: user
    password:
    driver-class-name: org.h2.Driver